### PR TITLE
created a view that will enable a user retrieve only notices created by him/he

### PR DESCRIPTION
**Pull request by CaptainVee**
this solves issue #259

### CODE REVIEW

**Review by danieliheonu — COMMENTED** [review]
did you test this code and it worked?

**Comment by CaptainVee** [comment]
after the latest pull request i did, i had to run python manage.py migrate before it worked. but before the it worked regardless

**Comment by danieliheonu** [comment]
I am talking about the end point you made, does it work because someone did similar and it didn't work

**Comment by CaptainVee** [comment]
it does work

**Comment by danieliheonu** [comment]
you tested it and you are sure

**Comment by CaptainVee** [comment]
yes sir

**Comment by danieliheonu** [comment]
okay. I will tell you when to pull and push again because I want to update the code

**Pull request closed without merging**
